version: "3.3"
   
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - db:/var/lib/postgresql/data/pgdata

  # api:
  #   container_name: api
  #   environment:
  #     - POSTGRES_DB=postgres
  #     - POSTGRES_USER=echoenergiadb
  #     - POSTGRES_PASSWORD=eVeSUAK4mQ8EH3y3LLzeXQM9
  #     - PYTHONUNBUFFERED=1
  #   image: api
  #   restart: always
  #   volumes:
  #     - ./api/:/code
  #     - rdh:/code/rdh
  #   ports: 
  #     - "5000:5000"

volumes:
  db:
  